### PR TITLE
Implementing home page carousel

### PR DESCRIPTION
**Pull request by wDushanin**
1. Implemented Carousel on homepage and updated Logo. 
2. Links should work EXCEPT chat link b/c not implemented yet.
3. Ignore the weird formatting issue on NavBar--will address this in a future PR.

### CODE REVIEW

**Comment by wDushanin** [comment]
@EthanPintoA am I good to merge after that last button fix?

**Review by EthanPintoA — CHANGES_REQUESTED** [review]
- Replace favicon.ico to new icon.
- Replace all code that use the old logo.jpeg (E.g. sign up form)
- Maybe add an item for About Us? Up to you.
- Change the alt attribute for the carousel images.

**Comment by wDushanin** [comment]
I don't know what the first bullet means.

**Comment by EthanPintoA** [comment]
favicon.ico is an image in the image folder. It's the icon that shows up in the web browser tab.

**Comment by wDushanin** [comment]
Do I just rename the new image to favicon.ico?

**Comment by EthanPintoA** [comment]
You probably need to convert it since it's an ico file

**Comment by wDushanin** [comment]
> You probably need to convert it since it's an ico file

Well, I feel dumb for not knowing that filetype XD

**Review by EthanPintoA — APPROVED** [review]

**Pull request merged**
