### PR TITLE
Refactor post forms and update delete button

### PR DESCRIPTION
**Pull request by EthanPintoA**
- Move post delete button to edit page and make it a Modal
- Refactor post forms

### CODE REVIEW

**Comment by wDushanin** [comment]
The line wrap isn't working on my end on posts, replies, or on the forum page.

**Comment by EthanPintoA** [comment]
Markdown requires that you have a space between lines.

**Comment by wDushanin** [comment]
Do we need to let the user know this somewhere? Or is this common usage?  I don't use forums enough to know.

**Review by wDushanin — APPROVED** [review]
All links and features work per my review.  I did not review the written code.

**Comment by EthanPintoA** [comment]
There's already a card in the backlog for that. It's yet to be implemented.

**Pull request merged**
